// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: alert.proto

#include "alert.pb.h"
#include "alert.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace alerts {

static const char* AlertCapturer_method_names[] = {
  "/alerts.AlertCapturer/SendAlert",
};

std::unique_ptr< AlertCapturer::Stub> AlertCapturer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AlertCapturer::Stub> stub(new AlertCapturer::Stub(channel, options));
  return stub;
}

AlertCapturer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendAlert_(AlertCapturer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AlertCapturer::Stub::SendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::alerts::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::alerts::Alert, ::alerts::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendAlert_, context, request, response);
}

void AlertCapturer::Stub::async::SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::alerts::Alert, ::alerts::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAlert_, context, request, response, std::move(f));
}

void AlertCapturer::Stub::async::SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAlert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::alerts::Result>* AlertCapturer::Stub::PrepareAsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::alerts::Result, ::alerts::Alert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendAlert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::alerts::Result>* AlertCapturer::Stub::AsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendAlertRaw(context, request, cq);
  result->StartCall();
  return result;
}

AlertCapturer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AlertCapturer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AlertCapturer::Service, ::alerts::Alert, ::alerts::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AlertCapturer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::alerts::Alert* req,
             ::alerts::Result* resp) {
               return service->SendAlert(ctx, req, resp);
             }, this)));
}

AlertCapturer::Service::~Service() {
}

::grpc::Status AlertCapturer::Service::SendAlert(::grpc::ServerContext* context, const ::alerts::Alert* request, ::alerts::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace alerts

