// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: alert.proto
#ifndef GRPC_alert_2eproto__INCLUDED
#define GRPC_alert_2eproto__INCLUDED

#include "alert.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace alerts {

class AlertCapturer final {
 public:
  static constexpr char const* service_full_name() {
    return "alerts.AlertCapturer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::alerts::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>> AsyncSendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>>(AsyncSendAlertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>> PrepareAsyncSendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>>(PrepareAsyncSendAlertRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>* AsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::alerts::Result>* PrepareAsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::alerts::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alerts::Result>> AsyncSendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alerts::Result>>(AsyncSendAlertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alerts::Result>> PrepareAsyncSendAlert(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alerts::Result>>(PrepareAsyncSendAlertRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, std::function<void(::grpc::Status)>) override;
      void SendAlert(::grpc::ClientContext* context, const ::alerts::Alert* request, ::alerts::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::alerts::Result>* AsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::alerts::Result>* PrepareAsyncSendAlertRaw(::grpc::ClientContext* context, const ::alerts::Alert& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendAlert_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendAlert(::grpc::ServerContext* context, const ::alerts::Alert* request, ::alerts::Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendAlert() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendAlert(::grpc::ServerContext* context, ::alerts::Alert* request, ::grpc::ServerAsyncResponseWriter< ::alerts::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendAlert<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendAlert() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::alerts::Alert, ::alerts::Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::alerts::Alert* request, ::alerts::Result* response) { return this->SendAlert(context, request, response); }));}
    void SetMessageAllocatorFor_SendAlert(
        ::grpc::MessageAllocator< ::alerts::Alert, ::alerts::Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::alerts::Alert, ::alerts::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendAlert(
      ::grpc::CallbackServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendAlert<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendAlert() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendAlert() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendAlert(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendAlert() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendAlert(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendAlert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendAlert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendAlert() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::alerts::Alert, ::alerts::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::alerts::Alert, ::alerts::Result>* streamer) {
                       return this->StreamedSendAlert(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendAlert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendAlert(::grpc::ServerContext* /*context*/, const ::alerts::Alert* /*request*/, ::alerts::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendAlert(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::alerts::Alert,::alerts::Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendAlert<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendAlert<Service > StreamedService;
};

}  // namespace alerts


#endif  // GRPC_alert_2eproto__INCLUDED
